server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: password
    dbname: peace
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 5m
  
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

app:
  environment: development
  log_level: info
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

log:
  level: info
  format: pretty
  time_format: "2006-01-02T15:04:05Z07:00"
  caller: false
  caller_skip: 2

auth:
  jwt:
    secret: dev-secret-key
    expiration: 24h
    refresh_expiration: 168h
